Repository hashicorp/terraform-provider-random, pull requests merged in 2022-09, with the labels that each got.

#304 Fix upgrade v2.2.1 -> v3.4.0 forces replacement
  CHANGELOG.md
  internal/provider/provider_test.go
  internal/provider/resource_password.go
  internal/provider/resource_password_test.go
  internal/provider/resource_string.go
  internal/provider/resource_string_test.go
Labels: bug, size/L

#305 Fix Breaking change of null keeper values between 3.3.2 and 3.4.0
  .github/workflows/test.yml
  CHANGELOG.md
  internal/planmodifiers/attribute.go
  internal/provider/resource_id.go
  internal/provider/resource_id_test.go
  internal/provider/resource_integer.go
  internal/provider/resource_integer_test.go
  internal/provider/resource_password.go
  internal/provider/resource_password_test.go
  internal/provider/resource_pet.go
  internal/provider/resource_pet_test.go
  internal/provider/resource_shuffle.go
  internal/provider/resource_shuffle_test.go
  internal/provider/resource_string.go
  internal/provider/resource_string_test.go
  internal/provider/resource_uuid.go
  internal/provider/resource_uuid_test.go
Labels: bug, size/XL

#312 resource/random_password+random_string: Prevent override_special differences upgrading from 3.3.2
  internal/planmodifiers/requires_replace.go
  internal/provider/resource_password.go
  internal/provider/resource_password_test.go
  internal/provider/resource_string.go
  internal/provider/resource_string_test.go
Labels: bug, size/L

#320 Updates for terraform-plugin-framework@v0.12.0
  go.mod
  go.sum
  internal/provider/provider.go
  internal/provider/resource_id.go
  internal/provider/resource_integer.go
  internal/provider/resource_password.go
  internal/provider/resource_pet.go
  internal/provider/resource_shuffle.go
  internal/provider/resource_string.go
  internal/provider/resource_uuid.go
Labels: dependencies, size/L

#326 .github/workflows: Add Terraform 1.3.x to testing matrix
  .github/workflows/test.yml
Labels: size/XS
