Repository hashicorp/terraform-provider-random, pull requests merged in 2022-08, with the labels that each got.

#275 Switching to protocol version 5
  .github/workflows/test.yml
  CHANGELOG.md
  docs/resources/password.md
  docs/resources/string.md
  internal/planmodifiers/attribute.go
  internal/provider/provider_test.go
  internal/provider/resource_id_test.go
  internal/provider/resource_integer_test.go
  internal/provider/resource_password.go
  internal/provider/resource_password_test.go
  internal/provider/resource_pet_test.go
  internal/provider/resource_shuffle_test.go
  internal/provider/resource_string.go
  internal/provider/resource_string_test.go
  internal/provider/resource_uuid_test.go
  main.go
  terraform-registry-manifest.json
Labels: documentation, size/XL

#291 Updating to Go 1.18
  .github/workflows/test.yml
  .go-version
  README.md
  go.mod
  go.sum
Labels: dependencies, size/M

#295 .github/workflows: Use upstream pr-size-labeler and ignore go.sum
  .github/workflows/pull-request.yml
Labels: size/XS

#297 Remove unneeded code from plan modifier
  internal/planmodifiers/attribute.go
Labels: size/S, technical-debt

#301 Fix Number numeric attribute plan modifier failed error on 3.4.0
  CHANGELOG.md
  internal/planmodifiers/attribute.go
  internal/provider/resource_password_test.go
Labels: bug, size/S
