Repository hashicorp/terraform-provider-random, pull requests merged in 2022-03, with the labels that each got.

#172 Update Documentation Again :D
  examples/resources/random_password/resource.tf
Labels: size/XS

#201 [Documentation] Adding default value
  docs/resources/string.md
Labels: documentation, size/XS

#207 GH Action to link incoming issues and pull-requests to the Terraform DevEx Team board
  .github/workflows/add-content-to-project.yml
Labels: size/S

#208 .github/workflows: Add 'go generate' testing for differences
  .github/workflows/test.yml
  docs/resources/password.md
  docs/resources/string.md
  internal/provider/string.go
Labels: documentation, size/S, technical-debt

#210 Update CODEOWNERS with new team name: @hashicorp/terraform-devex
  .github/CODEOWNERS
Labels: size/XS

#214 Preparing release 3.1.1
  .goreleaser.yml
  CHANGELOG.md
  docs/resources/id.md
  docs/resources/integer.md
  docs/resources/password.md
  docs/resources/pet.md
  docs/resources/shuffle.md
  docs/resources/string.md
  docs/resources/uuid.md
  go.mod
  go.sum
Labels: documentation, dependencies, size/M

#220 Bugfix: Restore randomness for `random_pet` resource
  CHANGELOG.md
  internal/provider/resource_pet.go
Labels: size/XS
