Repository hashicorp/terraform-provider-random, pull requests merged in 2022-04, with the labels that each got.

#229 Bump Development/Build Minimum Go Version to 1.17
  .github/workflows/test.yml
  .go-version
  README.md
  go.mod
Labels: dependencies, size/M

#231 Replace usage of deprecated fields in schema.Resource
  internal/provider/provider.go
  internal/provider/resource_id.go
  internal/provider/resource_integer.go
  internal/provider/resource_password.go
  internal/provider/resource_pet.go
  internal/provider/resource_shuffle.go
  internal/provider/resource_string.go
  internal/provider/resource_uuid.go
  internal/provider/string.go
  tools/tools.go
Labels: size/M

#234 random_string and random_password require checks on length
  CHANGELOG.md
  docs/resources/password.md
  docs/resources/string.md
  internal/provider/resource_string_test.go
  internal/provider/string.go
Labels: documentation, size/S

#240 Switch linting from go vet to golangci-lint
  .github/workflows/test.yml
  .golangci.yml
  GNUmakefile
  README.md
  internal/provider/resource_id.go
  internal/provider/resource_integer.go
  internal/provider/resource_integer_test.go
  internal/provider/resource_pet_test.go
  internal/provider/resource_shuffle.go
  internal/provider/resource_uuid.go
  internal/provider/resource_uuid_test.go
  internal/provider/string.go
Labels: size/L

#241 Test all minor Terraform versions
  .github/workflows/test.yml
  GNUmakefile
Labels: size/M

#242 Update documentation
  .github/CONTRIBUTING.md
  .github/SUPPORT.md
  DESIGN.md
  GNUmakefile
  README.md
  docs/index.md
  docs/resources/id.md
  docs/resources/integer.md
  docs/resources/pet.md
  docs/resources/shuffle.md
  examples/provider/provider.tf
  examples/resources/random_id/resource.tf
  examples/resources/random_integer/resource.tf
  examples/resources/random_pet/resource.tf
  examples/resources/random_shuffle/resource.tf
  scripts/errcheck.sh
  scripts/gofmtcheck.sh
Labels: documentation, size/XL

#248 Update Documentation
  docs/resources/integer.md
  docs/resources/pet.md
  examples/resources/random_integer/resource.tf
  internal/provider/resource_pet.go
Labels: documentation, size/XS

#158 accept min==max for random_integer resource
  internal/provider/resource_integer.go
Labels: size/XS
