Repository hashicorp/terraform-provider-random, pull requests merged in 2023-03, with the labels that each got.

#376 Update release workflow to use service account PAT
  .github/workflows/release.yml
Labels: size/S

#378 Updating to Go 1.19
  .changes/unreleased/NOTES-20230303-161959.yaml
  README.md
  go.mod
Labels: dependencies, size/XS, go

#383 .github/workflows: Test on Terraform 1.4.* versions
  .github/workflows/test.yml
Labels: size/XS

#386 Migrate acceptance tests to terraform-plugin-testing
  go.mod
  go.sum
  internal/provider/provider_test.go
  internal/provider/resource_id_test.go
  internal/provider/resource_integer_test.go
  internal/provider/resource_password_test.go
  internal/provider/resource_pet_test.go
  internal/provider/resource_shuffle_test.go
  internal/provider/resource_string_test.go
  internal/provider/resource_uuid_test.go
Labels: dependencies, size/XS, technical-debt
