Repository hashicorp/terraform-provider-random, pull requests merged in 2023-01, with the labels that each got.

#353 .github/workflows: Pin actions versions to SHAs
  .github/workflows/add-content-to-project.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issue-opened.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: size/S

#354 Update setup-go to use `go.mod`
  .github/workflows/release.yml
  .github/workflows/test.yml
  .go-version
Labels: size/S

#358 Add Jira automation
  .github/workflows/jira-sync.yml
  .github/workflows/send-to-jira.yml
Labels: size/M

#361 ci: merging `golangci-lint` rules
  .golangci.yml
Labels: size/XS
