Repository hashicorp/terraform-provider-random, pull requests merged in 2024-01, with the labels that each got.

#509 cdktf: update documentation
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/bytes.md
  docs/cdktf/python/resources/id.md
  docs/cdktf/python/resources/integer.md
  docs/cdktf/python/resources/password.md
  docs/cdktf/python/resources/pet.md
  docs/cdktf/python/resources/shuffle.md
  docs/cdktf/python/resources/string.md
  docs/cdktf/python/resources/uuid.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/bytes.md
  docs/cdktf/typescript/resources/id.md
  docs/cdktf/typescript/resources/integer.md
  docs/cdktf/typescript/resources/password.md
  docs/cdktf/typescript/resources/pet.md
  docs/cdktf/typescript/resources/shuffle.md
  docs/cdktf/typescript/resources/string.md
  docs/cdktf/typescript/resources/uuid.md
Labels: size/M

#510 Add `issues: write` permission to release workflow to close associated GitHub milestone
  .github/workflows/release.yml
Labels: size/XS

#514 cdktf: update documentation
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/bytes.md
  docs/cdktf/python/resources/id.md
  docs/cdktf/python/resources/integer.md
  docs/cdktf/python/resources/password.md
  docs/cdktf/python/resources/pet.md
  docs/cdktf/python/resources/shuffle.md
  docs/cdktf/python/resources/string.md
  docs/cdktf/python/resources/uuid.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/bytes.md
  docs/cdktf/typescript/resources/id.md
  docs/cdktf/typescript/resources/integer.md
  docs/cdktf/typescript/resources/password.md
  docs/cdktf/typescript/resources/pet.md
  docs/cdktf/typescript/resources/shuffle.md
  docs/cdktf/typescript/resources/string.md
  docs/cdktf/typescript/resources/uuid.md
Labels: size/S

#473 Update lint timeout
  .golangci.yml
Labels: size/XS

#521 .github/workflows: Update to hashicorp/ghaction-terraform-provider-release@v3
  .github/workflows/release.yml
Labels: size/XS

#525 Added GHA dependabot config for managing hashicorp actions
  .github/dependabot.yml
Labels: dependencies, size/XS
