Repository hashicorp/terraform-provider-random, pull requests merged in 2025-04, with the labels that each got.

#678 Update build.yml
  .github/workflows/build.yml
Labels: size/M

#684 chore: Prepare for `v3.7.2` release
  .changes/3.7.2.md
  .copywrite.hcl
  CHANGELOG.md
  META.d/_summary.yaml
  version/VERSION
Labels: size/XS

#685 chore: Final onboarding to CRT
  .copywrite.hcl
  .github/workflows/release.yml
  .goreleaser.yml
  README.md
Labels: size/L
