Repository hashicorp/terraform-provider-random, pull requests merged in 2025-02, with the labels that each got.

#625 ephemeral/password: Introduce a new ephemeral password resource
  .changes/unreleased/FEATURES-20250110-172233.yaml
  .changes/unreleased/NOTES-20250110-172526.yaml
  .gitignore
  docs/ephemeral-resources/password.md
  docs/resources/password.md
  examples/ephemeral-resources/random_password/ephemeral-resource.tf
  internal/provider/ephemeral_password.go
  internal/provider/ephemeral_password_test.go
  internal/provider/provider.go
  internal/provider/resource_password.go
Labels: enhancement, upstream-terraform, size/XL

#649 chore: Onboard random provider to CRT
  .release/ci.hcl
  .release/oss-release-metadata.hcl
  .release/release-metadata.hcl
  .release/security-scan.hcl
  .release/terraform-provider-random-artifacts.hcl
  version/VERSION
Labels: size/M

#652 cdktf: update documentation
  docs/cdktf/python/ephemeral-resources/password.md
  docs/cdktf/python/resources/password.md
  docs/cdktf/typescript/ephemeral-resources/password.md
  docs/cdktf/typescript/resources/password.md
Labels: size/M

#654 chore: Add build.yml for CRT releases
  .github/workflows/build.yml
Labels: size/M

#650 Prepare for `v3.7.0-alpha1` release
  .changes/3.7.0-alpha1.md
  CHANGELOG.md
Labels: size/XS

#660 docs: Adjust write-only wording to favor argument over attribute
  docs/ephemeral-resources/password.md
  internal/provider/ephemeral_password.go
Labels: documentation, size/XS

#651 Prepare for `v3.7.0` release
  .changes/3.7.0.md
  .changes/unreleased/FEATURES-20250110-172233.yaml
  .changes/unreleased/NOTES-20250110-172526.yaml
  CHANGELOG.md
  version/VERSION
Labels: size/S

#666 chore: Update release metadata HCL file
  .changes/unreleased/FEATURES-20250110-172233.yaml
  .changes/unreleased/NOTES-20250110-172526.yaml
  .release/ci.hcl
  .release/release-metadata.hcl
Labels: size/XS
